spring.application.name=schedule

# Traz o SQL no console (opcional)
spring.jpa.show-sql=true

# Atualiza a estrutura do banco sem apagar dados
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
