spring.application.name=schedule

# Mostrar SQL no console
spring.jpa.show-sql=true

# Atualiza tabelas automaticamente
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# Configuração para o Railway (MySQL)
spring.datasource.url=jdbc:mysql://mysql.railway.internal:3306/railway
spring.datasource.username=root
spring.datasource.password=DzORsACbJwOlKkQevfDMykffENoNrprT

# Porta dinâmica usada pelo Railway
server.port=${PORT:8080}
